---
# vim: set ft=ansible:

ubuntu_distro: bionic
ubuntu_mirror: http://us.archive.ubuntu.com/ubuntu/

ntp_timezone: Europe/Moscow

ntp_servers:
- 0.ru.pool.ntp.org
- 1.ru.pool.ntp.org
- 2.ru.pool.ntp.org
- 3.ru.pool.ntp.org

ntp_fallback_servers:
- 0.pool.ntp.org
- 1.pool.ntp.org
- 2.pool.ntp.org
- 3.pool.ntp.org

docker_bip: 10.201.0.2/24
docker_storage_driver: overlay2

sysctl_settings:  # all net.* are in docker-shadow role
  'fs.file-max': 51200
  'net.core.default_qdisc': fq
  'net.core.netdev_max_backlog': 4096
  'net.core.rmem_default': 65536
  'net.core.rmem_max': 67108864
  'net.core.somaxconn': 4096
  'net.core.wmem_default': 65536
  'net.core.wmem_max': 67108864
