---
# vim: set ft=ansible:

- name: copy fail2ban config
  become: true
  template:
    src: fail2ban.conf.j2
    dest: /etc/fail2ban/fail.d/shadowsocks.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
