---
# vim: set ft=ansible:

- name: pull images
  become: true
  command: docker pull {{ docker_image | quote }}
  register: docker_pull_result
  changed_when: >
    not (docker_pull_result.stdout_lines | last).startswith("Status: Image is up to date")
  notify: docker-shadow updated
