---
# vim: set ft=ansible:

- name: get my public IP
  ipify_facts:
  when: not(shadow_config.ip is defined)

- name: define own ip address
  set_fact:
    shadow_config: "{{ shadow_config | combine({'ip': ansible_facts.ipify_public_ip}) }}"
  when: not(shadow_config.ip is defined)

- name: create configuration file for docker shadow
  become: true
  copy:
    content: "{{ shadow_config | to_json }}"
    dest: /etc/docker-shadow.json
    owner: root
    group: root
    mode: 0644

- name: copy template run file for shadowsocks
  become: true
  template:
    src: shadow.sh.j2
    dest: /usr/share/docker-shadow.sh
    owner: root
    group: root
    mode: 0755

- name: copy systemd service file for shadowsocks
  become: true
  template:
    src: shadow.service.j2
    dest: /etc/systemd/system/shadow.service
    owner: root
    group: root
    mode: 0644
  notify: docker-shadow updated

- name: run shadowsocks
  become: true
  systemd:
    daemon_reload: yes
    name: "{{ systemd_service_name }}"
    state: started
    enabled: yes

- name: wait a couple of seconds to get container up and running
  pause:
    seconds: 10

- name: get config
  become: true
  command: docker exec {{ container_name | quote }} sh -c show
  changed_when: false
  register: output

- name: configuration of shadowsocks
  debug:
    msg: "{{ output.stdout | from_json }}"
